/**
 * The Personal Development library: ten curated pillars. Most hold 25 books;
 * Business holds 29 (the three Hormozi titles are kept as individual books
 * rather than one bundle entry), and Money and Biography hold 30.
 *
 * A recommendation shelf, not a different kind of content: tapping a book here
 * starts the same 7-day course search does. It exists so a reader who knows
 * they want to get better at negotiating, say, doesn't have to already know
 * which book to search for.
 *
 * These pillar names are also the topics a reader picks from at onboarding —
 * lib/genres.ts derives that list from this one, so the two can never drift
 * and a saved preference always resolves to a real shelf.
 */

export interface MasteryBook {
  /** Stable url-safe id, derived once here rather than recomputed per render. */
  slug: string;
  title: string;
  author: string;
}

export interface MasteryPillar {
  slug: string;
  name: string;
  /** One line shown under the pillar name on the category grid. */
  blurb: string;
  books: MasteryBook[];
}

/** "The Challenger Sale" -> "the-challenger-sale" */
export function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function shelf(titles: [string, string][]): MasteryBook[] {
  return titles.map(([title, author]) => ({ slug: slugify(title), title, author }));
}

export const MASTERY_PILLARS: MasteryPillar[] = [
  {
    slug: "sales",
    name: "Sales",
    blurb: "Persuasion, prospecting, and closing.",
    books: shelf([
      ["The Challenger Sale", "Brent Adamson"],
      ["The Psychology of Selling", "Brian Tracy"],
      ["Spin Selling", "Neil Rackham"],
      ["To Sell Is Human", "Daniel H. Pink"],
      ["Fanatical Prospecting", "Jeb Blount"],
      ["Sell or Be Sold", "Grant Cardone"],
      ["Little Red Book of Selling", "Jeffrey Gitomer"],
      ["Secrets of Closing the Sale", "Zig Ziglar"],
      ["Way of the Wolf", "Jordan Belfort"],
      ["Influence", "Robert Cialdini"],
      ["Gap Selling", "Keenan"],
      ["Sales EQ", "Jeb Blount"],
      ["New Sales. Simplified.", "Mike Weinberg"],
      ["The Ultimate Sales Machine", "Chet Holmes"],
      ["Selling 101", "Zig Ziglar"],
      ["The Sales Acceleration Formula", "Mark Roberge"],
      ["Pitch Anything", "Oren Klaff"],
      ["Objections", "Jeb Blount"],
      ["High-Profit Prospecting", "Mark Hunter"],
      ["The Art of Closing the Sale", "Brian Tracy"],
      ["Sell Different!", "Lee B. Salz"],
      ["You Can't Teach a Kid to Ride a Bike at a Seminar", "David Sandler"],
      ["Smart Calling", "Art Sobczak"],
      ["Insight Selling", "Mike Schultz"],
      ["The Go-Giver", "Bob Burg"],
    ]),
  },
  {
    slug: "negotiation",
    name: "Negotiation",
    blurb: "Leverage, framing, and hard conversations.",
    books: shelf([
      ["Never Split the Difference", "Chris Voss"],
      ["Getting to Yes", "Roger Fisher"],
      ["Bargaining for Advantage", "G. Richard Shell"],
      ["Negotiation Genius", "Deepak Malhotra"],
      ["Getting Past No", "William Ury"],
      ["You Can Negotiate Anything", "Herb Cohen"],
      ["The Art of Negotiation", "Michael Wheeler"],
      ["Crucial Conversations", "Kerry Patterson"],
      ["Negotiating the Impossible", "Deepak Malhotra"],
      ["Getting More", "Stuart Diamond"],
      ["Pre-Suasion", "Robert Cialdini"],
      ["Secrets of Power Negotiating", "Roger Dawson"],
      ["Ask for More", "Alexandra Carter"],
      ["Difficult Conversations", "Douglas Stone"],
      ["3-D Negotiation", "David Lax"],
      ["The Power of a Positive No", "William Ury"],
      ["Start with No", "Jim Camp"],
      ["Beyond Winning", "Robert Mnookin"],
      ["Negotiating at Work", "Deborah M. Kolb"],
      ["The Book of Real-World Negotiations", "Joshua N. Weiss"],
      ["The Negotiator's Fieldbook", "Christopher Honeyman"],
      ["Say Less, Get More", "Fotini Iconomopoulos"],
      ["Winning Together", "Bruno S. Frey"],
      ["Everything is Negotiable", "Gavin Kennedy"],
      ["Trump: The Art of the Deal", "Donald J. Trump"],
    ]),
  },
  {
    slug: "human-nature",
    name: "Human Nature",
    blurb: "Why people actually do what they do.",
    books: shelf([
      ["The Laws of Human Nature", "Robert Greene"],
      ["Sapiens", "Yuval Noah Harari"],
      ["Thinking, Fast and Slow", "Daniel Kahneman"],
      ["Man's Search for Meaning", "Viktor Frankl"],
      ["The 48 Laws of Power", "Robert Greene"],
      ["How to Win Friends & Influence People", "Dale Carnegie"],
      ["Behave", "Robert Sapolsky"],
      ["Quiet", "Susan Cain"],
      ["The Blank Slate", "Steven Pinker"],
      ["Predictably Irrational", "Dan Ariely"],
      ["The Righteous Mind", "Jonathan Haidt"],
      ["Outliers", "Malcolm Gladwell"],
      ["Talking to Strangers", "Malcolm Gladwell"],
      ["The Better Angels of Our Nature", "Steven Pinker"],
      ["Meditations", "Marcus Aurelius"],
      ["Lord of the Flies", "William Golding"],
      ["The Power of Habit", "Charles Duhigg"],
      ["Blink", "Malcolm Gladwell"],
      ["12 Rules for Life", "Jordan B. Peterson"],
      ["The Red Queen", "Matt Ridley"],
      ["Animal Farm", "George Orwell"],
      ["Games People Play", "Eric Berne"],
      ["Drive", "Daniel H. Pink"],
      ["The Selfish Gene", "Richard Dawkins"],
      ["Flow", "Mihaly Csikszentmihalyi"],
    ]),
  },
  {
    slug: "money",
    name: "Money",
    blurb: "Earning, investing, and compounding it.",
    books: shelf([
      ["The Psychology of Money", "Morgan Housel"],
      ["Rich Dad Poor Dad", "Robert Kiyosaki"],
      ["The Total Money Makeover", "Dave Ramsey"],
      ["The Intelligent Investor", "Benjamin Graham"],
      ["The Millionaire Next Door", "Thomas J. Stanley"],
      ["I Will Teach You to Be Rich", "Ramit Sethi"],
      ["The Richest Man in Babylon", "George S. Clason"],
      ["The Simple Path to Wealth", "JL Collins"],
      ["Money: Master the Game", "Tony Robbins"],
      ["Think and Grow Rich", "Napoleon Hill"],
      ["Principles", "Ray Dalio"],
      ["A Random Walk Down Wall Street", "Burton Malkiel"],
      ["Your Money or Your Life", "Vicki Robin"],
      ["Broke Millennial", "Erin Lowry"],
      ["The Little Book of Common Sense Investing", "John C. Bogle"],
      ["The Creature from Jekyll Island", "G. Edward Griffin"],
      ["Die with Zero", "Bill Perkins"],
      ["The Alchemy of Finance", "George Soros"],
      ["Financial Feminist", "Tori Dunlap"],
      ["How to Make Money in Stocks", "William O'Neil"],
      ["The Coffeehouse Investor", "Bill Schultheis"],
      ["One Up On Wall Street", "Peter Lynch"],
      ["The Art of Spending Money", "Morgan Housel"],
      ["Wealth Warrior", "Linda Garcia"],
      ["Finance for the People", "Paco de Leon"],
      // Financial education proper, rather than money mindset: this pillar is
      // where a reader looking for "Finance" lands, so it has to answer that.
      ["The Millionaire Fastlane", "MJ DeMarco"],
      ["Common Stocks and Uncommon Profits", "Philip A. Fisher"],
      ["The Bogleheads' Guide to Investing", "Taylor Larimore"],
      ["Financial Statements", "Thomas Ittelson"],
      ["The Barefoot Investor", "Scott Pape"],
    ]),
  },
  {
    slug: "business",
    name: "Business",
    blurb: "Building things that last and scale.",
    books: shelf([
      // Kept as three separate books rather than one "trilogy" entry, so each
      // gets its own cover, its own progress, and its own course.
      ["$100M Offers", "Alex Hormozi"],
      ["$100M Leads", "Alex Hormozi"],
      ["$100M Money Models", "Alex Hormozi"],
      ["Good to Great", "Jim Collins"],
      ["The E-Myth Revisited", "Michael Gerber"],
      ["The Innovator's Dilemma", "Clayton Christensen"],
      ["Built to Last", "Jim Collins"],
      ["Zero to One", "Peter Thiel"],
      ["Start with Why", "Simon Sinek"],
      ["Blue Ocean Strategy", "W. Chan Kim"],
      ["The Lean Startup", "Eric Ries"],
      ["Atomic Habits", "James Clear"],
      ["The Hard Thing About Hard Things", "Ben Horowitz"],
      ["Measure What Matters", "John Doerr"],
      ["High Output Management", "Andrew Grove"],
      ["Shoe Dog", "Phil Knight"],
      ["Competitive Strategy", "Michael Porter"],
      ["Scaling Up", "Verne Harnish"],
      ["Profit First", "Mike Michalowicz"],
      ["The Goal", "Eliyahu M. Goldratt"],
      ["Crossing the Chasm", "Geoffrey Moore"],
      ["Leaders Eat Last", "Simon Sinek"],
      ["Work Rules!", "Laszlo Bock"],
      ["The 4-Hour Workweek", "Tim Ferriss"],
      ["Deep Work", "Cal Newport"],
      ["Principles: Life and Work", "Ray Dalio"],
      ["Creativity, Inc.", "Ed Catmull"],
      ["The Outsiders", "William N. Thorndike"],
      ["The Law of Success in Sixteen Lessons", "Napoleon Hill"],
    ]),
  },
  {
    slug: "relentlessness",
    name: "Relentlessness",
    blurb: "Discipline, grit, and refusing to quit.",
    books: shelf([
      ["Can't Hurt Me", "David Goggins"],
      ["Relentless", "Tim S. Grover"],
      ["Grit", "Angela Duckworth"],
      ["Extreme Ownership", "Jocko Willink"],
      ["Unbroken", "Laura Hillenbrand"],
      ["Endurance", "Alfred Lansing"],
      ["The Obstacle Is the Way", "Ryan Holiday"],
      ["Discipline Equals Freedom", "Jocko Willink"],
      ["Never Finished", "David Goggins"],
      ["The War of Art", "Steven Pressfield"],
      ["Mindset", "Carol S. Dweck"],
      ["Antifragile", "Nassim Nicholas Taleb"],
      ["The Comfort Crisis", "Michael Easter"],
      ["Winning", "Tim S. Grover"],
      ["Lone Survivor", "Marcus Luttrell"],
      ["Make Your Bed", "William H. McRaven"],
      ["The 5 AM Club", "Robin Sharma"],
      ["The Art of War", "Sun Tzu"],
      ["Living with a SEAL", "Jesse Itzler"],
      ["Level Up", "Rob Dial"],
      ["The 10X Rule", "Grant Cardone"],
      ["Ego Is the Enemy", "Ryan Holiday"],
      ["Total Recall", "Arnold Schwarzenegger"],
      ["The Spartan Way", "Joe De Sena"],
      ["The Way of the SEAL", "Mark Divine"],
    ]),
  },
  {
    slug: "leadership",
    name: "Leadership",
    blurb: "Leading teams people don't want to leave.",
    books: shelf([
      ["The 21 Irrefutable Laws of Leadership", "John C. Maxwell"],
      ["The 7 Habits of Highly Effective People", "Stephen R. Covey"],
      ["Dare to Lead", "Brené Brown"],
      ["The Five Dysfunctions of a Team", "Patrick Lencioni"],
      ["Turn the Ship Around!", "L. David Marquet"],
      ["Radical Candor", "Kim Scott"],
      ["Multipliers", "Liz Wiseman"],
      ["Primal Leadership", "Daniel Goleman"],
      ["The Leadership Challenge", "James M. Kouzes"],
      ["Team of Rivals", "Doris Kearns Goodwin"],
      ["Leadership in Turbulent Times", "Doris Kearns Goodwin"],
      ["The Culture Code", "Daniel Coyle"],
      ["The Infinite Game", "Simon Sinek"],
      ["Trillion Dollar Coach", "Eric Schmidt"],
      ["No Rules Rules", "Reed Hastings"],
      ["The First 90 Days", "Michael D. Watkins"],
      ["Leadership Strategy and Tactics", "Jocko Willink"],
      ["The Coaching Habit", "Michael Bungay Stanier"],
      ["Developing the Leader Within You", "John C. Maxwell"],
      ["The Making of a Manager", "Julie Zhuo"],
      ["Wooden on Leadership", "John Wooden"],
      ["It's Your Ship", "D. Michael Abrashoff"],
      ["Leadership and Self-Deception", "The Arbinger Institute"],
      ["Tribes", "Seth Godin"],
      ["Good Leaders Ask Great Questions", "John C. Maxwell"],
    ]),
  },
  {
    slug: "biography",
    name: "Biography",
    blurb: "How the people who did it actually did it.",
    books: shelf([
      ["Elon Musk", "Walter Isaacson"],
      ["Steve Jobs", "Walter Isaacson"],
      ["Titan: The Life of John D. Rockefeller, Sr.", "Ron Chernow"],
      ["The Autobiography of Andrew Carnegie", "Andrew Carnegie"],
      ["The Everything Store", "Brad Stone"],
      ["Invent and Wander", "Jeff Bezos"],
      ["Benjamin Franklin: An American Life", "Walter Isaacson"],
      ["Made in America", "Sam Walton"],
      ["Losing My Virginity", "Richard Branson"],
      ["Long Walk to Freedom", "Nelson Mandela"],
      ["Becoming", "Michelle Obama"],
      ["My Life and Work", "Henry Ford"],
      ["Alexander Hamilton", "Ron Chernow"],
      ["Einstein: His Life and Universe", "Walter Isaacson"],
      ["Leonardo da Vinci", "Walter Isaacson"],
      ["The Snowball", "Alice Schroeder"],
      ["Open", "Andre Agassi"],
      ["Greenlights", "Matthew McConaughey"],
      ["Will", "Will Smith"],
      ["Educated", "Tara Westover"],
      ["The Ride of a Lifetime", "Robert Iger"],
      ["Onward", "Howard Schultz"],
      ["Hard Drive", "James Wallace"],
      ["Source Code", "Bill Gates"],
      ["Grinding It Out", "Ray Kroc"],
      ["That Will Never Work", "Marc Randolph"],
      ["Born a Crime", "Trevor Noah"],
      ["I Am Malala", "Malala Yousafzai"],
      ["Churchill: Walking with Destiny", "Andrew Roberts"],
      ["The Wright Brothers", "David McCullough"],
    ]),
  },
  {
    slug: "psychology",
    name: "Psychology",
    blurb: "The mind, the shadow, and what drives you.",
    books: shelf([
      ["Man and His Symbols", "Carl Jung"],
      ["Modern Man in Search of a Soul", "Carl Jung"],
      ["Memories, Dreams, Reflections", "Carl Jung"],
      ["The Undiscovered Self", "Carl Jung"],
      ["The Archetypes and the Collective Unconscious", "Carl Jung"],
      ["The Body Keeps the Score", "Bessel van der Kolk"],
      ["Emotional Intelligence", "Daniel Goleman"],
      ["The Interpretation of Dreams", "Sigmund Freud"],
      ["Civilization and Its Discontents", "Sigmund Freud"],
      ["Attached", "Amir Levine"],
      ["Maybe You Should Talk to Someone", "Lori Gottlieb"],
      ["The Four Agreements", "Don Miguel Ruiz"],
      ["Learned Optimism", "Martin Seligman"],
      ["Feeling Good", "David D. Burns"],
      ["The Happiness Hypothesis", "Jonathan Haidt"],
      ["Stumbling on Happiness", "Daniel Gilbert"],
      ["Nudge", "Richard H. Thaler"],
      ["Misbehaving", "Richard H. Thaler"],
      ["The Paradox of Choice", "Barry Schwartz"],
      ["Self-Compassion", "Kristin Neff"],
      ["No Bad Parts", "Richard Schwartz"],
      ["Adult Children of Emotionally Immature Parents", "Lindsay C. Gibson"],
      ["The Drama of the Gifted Child", "Alice Miller"],
      ["Owning Your Own Shadow", "Robert A. Johnson"],
      ["The Denial of Death", "Ernest Becker"],
    ]),
  },
  {
    slug: "health",
    name: "Health & Energy",
    blurb: "Sleep, training, food, and lasting energy.",
    books: shelf([
      ["Why We Sleep", "Matthew Walker"],
      ["Outlive", "Peter Attia"],
      ["Breath", "James Nestor"],
      ["Lifespan", "David A. Sinclair"],
      ["How Not to Die", "Michael Greger"],
      ["The Obesity Code", "Jason Fung"],
      ["Why We Get Fat", "Gary Taubes"],
      ["Spark", "John J. Ratey"],
      ["Bigger Leaner Stronger", "Michael Matthews"],
      ["Starting Strength", "Mark Rippetoe"],
      ["The 4-Hour Body", "Timothy Ferriss"],
      ["Born to Run", "Christopher McDougall"],
      ["Endure", "Alex Hutchinson"],
      ["Peak Performance", "Brad Stulberg"],
      ["The Sleep Solution", "W. Chris Winter"],
      ["Eat to Beat Disease", "William W. Li"],
      ["The Blue Zones", "Dan Buettner"],
      ["In Defense of Food", "Michael Pollan"],
      ["Genius Foods", "Max Lugavere"],
      ["The Circadian Code", "Satchin Panda"],
      ["Deep Nutrition", "Catherine Shanahan"],
      ["The Oxygen Advantage", "Patrick McKeown"],
      ["Younger Next Year", "Chris Crowley"],
      ["Good Energy", "Casey Means"],
      ["The Wim Hof Method", "Wim Hof"],
    ]),
  },
];

export function pillarBySlug(slug: string): MasteryPillar | undefined {
  return MASTERY_PILLARS.find((p) => p.slug === slug);
}

export function bookBySlug(pillarSlug: string, bookSlug: string): MasteryBook | undefined {
  return pillarBySlug(pillarSlug)?.books.find((b) => b.slug === bookSlug);
}
